# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

target '异步绘制圆形头像' do
  # Uncomment this line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!
pod 'Masonry'

  # Pods for 异步绘制圆形头像

end
