# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

target 'UI-顶部放大效果Demo' do
  # Uncomment this line if you're using Swift or would like to use dynamic frameworks
use_frameworks!
pod 'AFNetworking'
pod 'YYWebImage'

  # Pods for UI-顶部放大效果Demo

end
